# Generated by Django 5.1.5 on 2025-02-05 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipo_usuario', models.CharField(choices=[('dono_conta', 'Usuario'), ('gerente_banco', 'Gerente do Banco')], default='dono_conta', max_length=20)),
                ('email', models.EmailField(max_length=62, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('role', models.CharField(choices=[('dono_conta', 'Usuario'), ('gerente_banco', 'Gerente do Banco')], default='Usuario', max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='groups_usuario_customizado', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions_usuario_customizado', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
