# Generated by Django 5.1.5 on 2025-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('gerente_banco', 'Gerente do Banco')], default='Usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('gerente_banco', 'Gerente do Banco')], default='usuario', max_length=20),
        ),
    ]
