# Generated by Django 5.1.5 on 2025-02-06 18:20

import autenticacao.validators.cpf_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_user_role_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), autenticacao.validators.cpf_validator.validate_cpf], verbose_name='CPF'),
        ),
    ]
